language: c
matrix:
  include:
    - os: osx
      env: TARGET_MACHINE=i3osx
    - os: osx
      env: TARGET_MACHINE=ti3osx
    - os: osx
      env: TARGET_MACHINE=a6osx
    - os: osx
      env: TARGET_MACHINE=ta6osx
    - os: linux
      env: TARGET_MACHINE=i3le
      sudo: required
    - os: linux
      env: TARGET_MACHINE=ti3le
      sudo: required
    - os: linux
      env: TARGET_MACHINE=a6le
    - os: linux
      env: TARGET_MACHINE=ta6le
dist: trusty
addons:
  apt:
    packages:
      - gcc-multilib
      - lib32ncurses5-dev
      - libx32ncurses5-dev
script:
  - .travis/dobuild.sh
